spring:
  application:
    name: linkly
  datasource:
    url: jdbc:postgresql://localhost:5432/linkly
    username: linkly
    password: linkly
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
